apiVersion: v1
entries:
  k8s-ca-injector:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2025-11-08T17:51:26.263967336Z"
    description: MutatingAdmissionWebhook to inject certificates into pods automatically
      based on simple annotations in kubernetes
    digest: e90818d23eed39f89ef60b4f9022b19f46ad8b0e0950d726a43ff0091f165726
    name: k8s-ca-injector
    urls:
    - https://omidiyanto.github.io/k8s-ca-injector/charts/k8s-ca-injector-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-08T17:51:26.263538405Z"
